version: "3.8"
services:
  php_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: santaelenap
    container_name: santaelenap
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
